import "./globals.css";
import { Roboto } from "next/font/google";
import { Inter } from "next/font/google";
import NavHeader from "@/components/NavHeader/NavHeader";
import type { Metadata } from "next";

import styles from "./layout.module.scss";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <div className={styles.head}>
          <div className={styles.contaiter}>
            <header className={styles.header}>
              <NavHeader />
            </header>
          </div>
        </div>

        <div className={styles.contaiter}>{children}</div>
      </body>
    </html>
  );
}
